swagger: '2.0' 
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host:   localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts:
     post:
      security:
        - Bearer: []
      tags:
        - User Acount
      summary: Account list
      description: API for transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: User transactions retrieved success
          schema:
            $ref: '#/definitions/Accounts'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}/transactions:
    post:
      security:
        - Bearer: []
      tags:
        - User Acount
      summary: Transactions list
      description: API for transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: accountId
          description: target account id
          type : integer
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User transactions retrieved success
          schema:
            $ref: '#/definitions/AccountTransactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}/transactions/{transactionId} :
    put:
      security:
          - Bearer: []
      tags:
          - User Acount
      summary: update category
      description: API for updating a transaction category
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: accountId
          description: target account id
          type : integer
          required: true
        - in: path
          name: transactionId
          description: target transaction id
          type : integer
          required: true  
        - in: body
          name: body
          description: Update user transactions attributes
          required: true
          schema:
            $ref: '#/definitions/TransactionAttributes'
      produces:
        - application/json
      responses:
        '200':
          description: transaction retrieved success
          schema:
            $ref: '#/definitions/Accounts'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  Accounts:
    properties:
      accounts : 
        type: array
        description : array with all users acount transactions
        items: 
          $ref: "#/definitions/AccountTransactions"
  AccountTransactions :
    type : object
    properties:        
      accountId: 
        type: number
        description: account id
      transactions: 
        type: array
        description: array with  transactions
        items:
          $ref: "#/definitions/ListTransactions"             
  ListTransactions :
    type : object
    description: transaction for the current mounth
    properties:
      transactionId: 
        type: number
        description: transaction id
      date: 
        type: string
        description: transaction date
      description: 
        type: string
        description: a string to describe the transaction
      amount: 
        type: number
        description: amount value of transaction
      balance: 
        type: number
        description: balance value of transaction
      transactionType: 
        type: string
        description: transaction type
      attributes: 
        $ref : '#/definitions/TransactionAttributes'
  TransactionAttributes:
    type : object
    properties:
      category: 
        type : string
        description: transaction category
      notes: 
        type: string
        description: transaction notes